name: Build & Deploy to Dev
run-name: ${{ gitea.actor }} is testing ${{ gitea.repository }} 🚀
on: [push]

jobs:
  build_and_deploy:
    runs-on: debian
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build
        run: mvn clean install

      - name: Get jar name
        id: jar_info
        run: |
          # Get artifactId and version from pom.xml
          ARTIFACT_ID=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='artifactId']/text()" pom.xml)
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          JAR_NAME="${ARTIFACT_ID}-${VERSION}.jar"
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

      - name: Remove old jars on server
        run: |
          ssh -o StrictHostKeyChecking=no dev@magicalsky.fr -p 42 "rm -f /home/dev/final121/plugins/${ARTIFACT_ID}-*.jar"

      - name: Copy new jar to server
        run: |
          scp -o StrictHostKeyChecking=no target/${JAR_NAME} -P 42 dev@magicalsky.fr:/home/dev/final121/plugins/